/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/home_view/Accordion.vue')['default']
    AccordionCard: typeof import('./src/components/home_view/Accordion/accordionCard.vue')['default']
    BubbleCard: typeof import('./src/components/home_view/QCodeCard/components/BubbleCard.vue')['default']
    Card: typeof import('./src/components/home_view/QCodeCard/components/Card.vue')['default']
    CardDetail: typeof import('./src/components/home_view/Accordion/cardDetail.vue')['default']
    Carousel: typeof import('./src/components/home_view/carousel/components/Carousel.vue')['default']
    CarouselItem: typeof import('./src/components/home_view/carousel/components/CarouselItem.vue')['default']
    ContentItem: typeof import('./src/components/common/SolutionTab/ContentItem.vue')['default']
    Drawer: typeof import('./src/components/common/Header/SimplifiedVersion/Drawer.vue')['default']
    DropContent: typeof import('./src/components/common/SolutionTab/DropContent.vue')['default']
    DropNav: typeof import('./src/components/common/SolutionTab/DropNav.vue')['default']
    DropNews: typeof import('./src/components/common/SolutionTab/DropNews.vue')['default']
    DropSearch: typeof import('./src/components/common/SolutionTab/DropSearch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    Framecard: typeof import('./src/components/home_view/framecard/index.vue')['default']
    FrameCard: typeof import('./src/components/home_view/FrameCard.vue')['default']
    FrameCardItem: typeof import('./src/components/home_view/framecard/components/FrameCardItem.vue')['default']
    FrameCardList: typeof import('./src/components/home_view/framecard/components/FrameCardList.vue')['default']
    FrameIcon: typeof import('./src/components/common/FrameIcon.vue')['default']
    FrameTab: typeof import('./src/components/home_view/FrameTab/index.vue')['default']
    Header: typeof import('./src/components/common/Header/index.vue')['default']
    HeaderSearch: typeof import('./src/components/common/HeaderSearch.vue')['default']
    HeaderSearchInput: typeof import('./src/components/common/HeaderSearchInput/index.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Index: typeof import('./src/components/common/Header/SimplifiedVersion/Index.vue')['default']
    Indicator: typeof import('./src/components/home_view/carousel/components/Indicator.vue')['default']
    Item: typeof import('./src/components/home_view/FrameTab/item.vue')['default']
    ItemList: typeof import('./src/components/home_view/QCodeCard/components/ItemList.vue')['default']
    Login: typeof import('./src/components/home_view/Login.vue')['default']
    MainDropdown: typeof import('./src/components/common/HeaderSearchInput/MainDropdown.vue')['default']
    Menu: typeof import('./src/components/common/Header/SimplifiedVersion/Menu.vue')['default']
    NavList: typeof import('./src/components/common/Header/NavList.vue')['default']
    QCodeCard: typeof import('./src/components/home_view/QCodeCard/index.vue')['default']
    ResultDropdown: typeof import('./src/components/common/HeaderSearchInput/ResultDropdown.vue')['default']
    RightOperations: typeof import('./src/components/common/Header/RightOperations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/common/HeaderSearchInput/SearchInput.vue')['default']
    SearchOptions: typeof import('./src/components/common/SearchOptions.vue')['default']
    SearchResult: typeof import('./src/components/common/SearchResult.vue')['default']
    SolutionTab: typeof import('./src/components/common/SolutionTab/SolutionTab.vue')['default']
    Tab: typeof import('./src/components/home_view/FrameTab/tab.vue')['default']
    User: typeof import('./src/components/common/Header/SimplifiedVersion/User.vue')['default']
    VideoCarousel: typeof import('./src/components/home_view/carousel/VideoCarousel.vue')['default']
  }
}
